### ISSUE TITLE
IE 11 Support

### ISSUE THREAD

**Issue by wilbert-abreu** [jaredLunde/react-hook#1]
Currently arrow functions need to be transpired by babel in order to support this in IE11.

Please use `@babel/plugin-transform-arrow-functions`.

**Comment by jaredLunde** [comment]
IMO it is the end user's obligation to transpile to the browser targets they desire. This means transpiling your `node_modules`. I have learned through experience that you simply cannot trust external libraries to support any specific target. As such, these libraries only transpile with ESM and CJS targets in mind because it is a much more reasonable expectation that I should be able to `require()` a module.

**Comment by jaredLunde** [comment]
FWIW this is in line with the assumption that `create-react-app` makes.

**Comment by wilbert-abreu** [comment]
https://github.com/facebook/create-react-app/issues/1125#issuecomment-264158377

From `gaearon`, responding to `The only answer to this is, IMHO, to also transpile external dependencies. Is this supported by create-react-app?`

```
No, this is not supported because builds will get much slower. We don't recommend using libraries that don't precompile their code to ES5 but are supposed to be usable in ES5.

We will fix the Uglify problem in the future by using Babili. However it still means that even uglified code will still be ES6 if that's what your dependencies are shipping.

With time it won't matter as much because mainstream browsers will support ES6. Until then I recommend to use libraries that take care of transpilation step.
```

**Comment by jaredLunde** [comment]
As quoted later in the thread, this shipped in v2
https://github.com/facebook/create-react-app/issues/1125#issuecomment-426120762

**Comment by wilbert-abreu** [comment]
Don't sure what you mean by `this shipped in v2`. I think you may be thinking of their opinions on polyfills https://github.com/facebook/create-react-app/blob/master/packages/react-app-polyfill/README.md `Note that support for older browsers is now opt-in to reduce the polyfill size.`. Doing what I'm suggesting will not increase the amount of code. 

What is the downside?

**Comment by jaredLunde** [comment]
This particular transformation doesn't drastically increase the bundle size, but the logical argument remains: the end-user should pick their own target. Turning on `@babel/plugin-transform-arrow-functions` alone won't make any particular lib IE 11 compatible as the issue title suggests. If I go on to use `Object.keys()` somewhere, IE 11 breaks again. It's just not my responsibility to maintain your target. I use a build system that transpiles `node_modules` and would therefore gain nothing from this proposal. Nothing is stopping you from copying/pasting any particular library and doing the transformation yourself - it's MIT licensed.
