### ISSUE TITLE
[resize-observer] Multiple callbacks on a single html element

### ISSUE THREAD

**Issue by albertputrapurnama** [jaredLunde/react-hook#110]
**Is your feature request related to a problem? Please describe.**
Unable to add multiple callbacks on a single HTML element. When I do `useResizeObserver(target, callback);` and target is the same on multiple components, only the latest callback will be called.

**Describe the solution you'd like**
`useResizeObserver` should not override existing callback on elements. So I propose changing callback map from `Map<any, UseResizeObserverCallback>` to `Map<any, Array<UseResizeObserverCallback>>`. Then changes `subscribe` and `unsubscribe` callback too. More on this on the PR

**Describe alternatives you've considered**
I have not considered other alternatives

**Additional context**
None

**Comment by tsmithATX** [comment]
I'm experiencing the same issue, kinda seemed like from the docs this was already handled

**Comment by albertputrapurnama** [comment]
Try out the PR @tsmithATX, I'm using my branch for current development, hope it helps you
