### ISSUE TITLE
[resize-observer, size] Replace unmaintained resize-observer-polyfill with @juggle/resize-observer

### ISSUE THREAD

**Issue by cascornelissen** [jaredLunde/react-hook#122]
**Is your feature request related to a problem? Please describe.**
The `useResizeObserver` and `useSize` hooks use [`resize-observer-polyfill`](https://www.npmjs.com/package/resize-observer-polyfill) which hasn't been updated in 3 years and has a really annoying issue with its types since TS 4.2. This is causing many users to stick to TS 4.1 in the hopes of a new release of `resize-observer-polyfill` but the owner hasn't responded in months.

See https://github.com/que-etc/resize-observer-polyfill/issues/80 and https://github.com/que-etc/resize-observer-polyfill/issues/83 for additional information.

**Describe the solution you'd like**
Use [`@juggle/resize-observer`](https://www.npmjs.com/package/@juggle/resize-observer) instead of [`resize-observer-polyfill`](https://www.npmjs.com/package/resize-observer-polyfill) as a drop-in replacement for `@react-hook/size` and `@react-hook/resize-observer`.

**Describe alternatives you've considered**
None.

**Additional context**
I can try creating a PR if this change is wanted. Please let me know which versions of IE need to be supported as `@juggle/resize-observer` needs additional polyfills for IE9/IE10 but supports IE11 out of the box.

**Comment by cascornelissen** [comment]
@jaredLunde, sorry to ping you but this one is blocking updates to newer TS versions in some of our projects so I'd love to hear if you're interested in a PR for this?

**Comment by jaredLunde** [comment]
Yes Id' take a PR, thanks!

**Comment by cascornelissen** [comment]
Thanks! Just checked npm to see if the latest release was available already and I noticed the README still referenced the old package so I fixed that in #127 which also update the dependency for `@react-hook/size` to ensure the deeper dependency is gone.
