### ISSUE TITLE
Support breakpoints in useWindowSize

### ISSUE THREAD

**Issue by danvk** [jaredLunde/react-hook#13]
I only care about whether my window width crosses a threshold from a CSS breakpoint, I don't need an update on every resize frame.

If I can build a hook for this using `useWidthWidth`, I'd love to know how!

```ts
function useIsWideWindow() {
  const width = useWindowWidth();
  return width > 1000;
}
```

**Comment by jaredLunde** [comment]
I don't think you'll have issues with frame updates as the hook is debounced by default. However, you could set the debounce wait time arbitrarily high once your threshold is met.

```js
import {useWindowWidth} from '@react-hook/window-size'

function useIsWideWindow() {
   const [thresholdMet, setThresholdMet] = useState(false)
   // only update once per second if the threshold is met
   const useWindowWidth(0, {wait: thresholdMet ? 1000 : 100})

  useEffect(() => {
   setThresholdMet(width > 1000)
  }, [width])
  
  return thresholdMet
}
```

Overall though the hook you want is something that uses the JS api for media queries:
https://github.com/streamich/use-media

**Comment by danvk** [comment]
Thanks for the pointer @jaredLunde, `use-media` was exactly what I was looking for.

I don't think the debouncing solution will work since you could always shrink the window after expanding it, and that transition should be responsive, too.
