### ISSUE TITLE
isOver is not working properly

### ISSUE THREAD

**Issue by alielkhateeb** [jaredLunde/react-hook#14]
Hi, 

Thanks a lot for the great work.

There is an issue with `isOver`, I have created a [sandbox](https://codesandbox.io/s/ecstatic-wave-coi66) to show you.

You'll see `isOver` initially is `false` but when you go in the grey div, it turns to `true` and will never go back to `false` (Unless you leave the grey area slowly), even `clientX` and `clientY` will not be `null` if the mouse doesn't leave the grey area slowly.

NOTE: You have to move the mouse out of the grey div quickly to reproduce.

**Comment by jaredLunde** [comment]
Whoa! Bad news. Sorry about that. Just put out a fix @react-hook/mouse-position@3.0.2

Thanks for the report!

**Comment by alielkhateeb** [comment]
@jaredLunde Thanks for the fix, but it causes an issue when you click inside the grey area it stops reporting clientX and clientY completely.

**Comment by jaredLunde** [comment]
Well dang it. So the real problem is this is the only hook that I didn’t create a full test suite for, for some reason. I’ll remedy that this morning. Thanks again for reporting this stuff, creating the sandbox, being patient.

**Comment by alielkhateeb** [comment]
Thank you very much for your prompt replies and constant updates.

I could help if you want :) just please add "Development" section to the docs so I can follow to install things on my localhost.

Thanks again, have a great evening.

**Comment by jaredLunde** [comment]
I believe I've fixed all of the issues with `3.0.3`, however if you come across anything else or want to contribute other stuff to `react-hook`, I added a contributing section to the README https://github.com/jaredLunde/react-hook#contributing

**Comment by alielkhateeb** [comment]
@jaredLunde Thank you very much for working on this.
