### ISSUE TITLE
I don't think native ResizeObserver is ever used

### ISSUE THREAD

**Issue by em** [jaredLunde/react-hook#145]
Looking at https://github.com/jaredLunde/react-hook/blob/master/packages/resize-observer/src/index.tsx

It seems you are using https://github.com/juggle/resize-observer

According to their docs, they expect the user to detect if window.ResizeObserver exists themselves, and use the polyfill if it doesn't. 

> This will use the ponyfilled version of ResizeObserver, even if the browser supports ResizeObserver natively.

Seems like the native ResizeObserver will never be used.

**Comment by daemon-byte** [comment]
yeh my understand is it should be done like this. If I have some time I'll try and create a patch 

import { ResizeObserver as Polyfill } from '@juggle/resize-observer';
const ResizeObserver = window.ResizeObserver || Polyfill;
