### ISSUE TITLE
useLatest() creates reference to a value from the previous render

### ISSUE THREAD

**Issue by kherock** [jaredLunde/react-hook#156]
**Describe the bug**
When I call `useLatest`, I expect to receive a ref object containing the value I pass to it. The current implementation updates the value with a `useEffect` callback. This will eventually update the ref, but by then, the code that actually needs the new value to render the component has already run.

**To Reproduce**
```tsx
function ComponentWithLatestRef() {
  const value = compute();
  const valueRef = useLatest(value);
  console.log(value === valueRef.current); // `false` when value differs from the last render
  useHook(opts, valueRef); // receives an old value
  
  return <div>...</div>
}
```

**Expected behavior**
The ref should be updated inline while the component renders. The existing behavior would be more accurately described by `usePreviousAndUpdate(value)`.

**Additional context**
This is present in `@react-hook/latest` 1.0.3

**Comment by jaredLunde** [comment]
That's how it's supposed to work. What you're doing by reading the `current` value during the render is considered a side effect.

```tsx
function ComponentWithLatestRef() {
  const value = compute();
  const valueRef = useLatest(value);
  React.useEffect(() => {
    console.log(value === valueRef.current); // `false` when value differs from the last render
  })
  useHook(opts, valueRef); // receives an old value
  
  return <div>...</div>
}
```

The above will display the correct value.  What you're looking for is perhaps the `usePrevious()` hook.

**Comment by kherock** [comment]
Ok, thanks for explaining, I'm not trying to argue with what it's actually intended to do. The linked repo does at least mention that it hooks into the `useEffect` lifecycle, whereas the wording in the README here only mentions that it updates on _each invocation_. There's some ambiguity in that, and I don't expect the examples to cover all potential use cases.

**Comment by jaredLunde** [comment]
You can learn more here:

- https://github.com/reactjs/rfcs/blob/useevent/text/0000-useevent.md
- https://overreacted.io/a-complete-guide-to-useeffect/#each-render-has-its-own-props-and-state

It ensures the value of `current` is isolated to the current render. In concurrent mode the same component/hook may render .... concurrently.
