### ISSUE TITLE
Where can I find packages changelogs?

### ISSUE THREAD

**Issue by drazik** [jaredLunde/react-hook#157]
Hello,

First, thanks a lot for these great hooks :heart_eyes: 

I am using some of them in a project. I am upgrading dependencies, and some hooks have new versions. I wanted to check what's new, but I couldn't find any changelogs. Do you generate some? If yes, where can I find them?

Thanks.

**Comment by aurbano** [comment]
Any plans on adding them?

It'd be a lot easier to upgrade if we knew what to look out for

**Comment by jaredLunde** [comment]
No. Most haven't changed in years. They're simple packages.

**Comment by jun-regcentric** [comment]
Regardless of the package is simple, it would be good to know what motivates into bumping the major version.

Jumping from v1 to v2 will put an impression that there might some breaking changes, and that's what we are curious about before really upgrading specific package. And it is hard to confirm without any changelogs for us to check.

<img width="1255" height="108" alt="Image" src="https://github.com/user-attachments/assets/fdfabcfc-99c0-4515-8da6-1e4b0a3d99fd" />
