### ISSUE TITLE
[Mouse Position] on phone when there are elements in the scene is malfunctioning

### ISSUE THREAD

**Issue by alielkhateeb** [jaredLunde/react-hook#16]
Hi,

This one is a bit tough but I'll try to explain as much as I can.

after adding a child element to the grey area, somehow tracking the touch drag is interrupted.

![bug](https://user-images.githubusercontent.com/20101678/73377611-47146e80-42fa-11ea-9bc3-5b7a9128ec08.gif)

## Steps to reproduce
In this [sandbox](https://codesandbox.io/s/ecstatic-wave-coi66) toggle device toolbar from devTools in chrome and you'll see when you click and drag from bottom to top, somehow in the middle it stops tracking `clientX` and `clientY` or `pageX`, `pageY` even though I haven't released the mouse click.

Thank you in advance!

**Comment by jaredLunde** [comment]
Hmm this is a weird one. It only happens if I move my finger up the device, not down, and only if I start from the bottom and move up. I can start from the top, move down and back up and it works fine. I'll have to do some digging. Perhaps playing with [touch-action](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action) would be a quick fix in the user-space.

**Comment by jaredLunde** [comment]
Oh, actually I think I have an idea.

**Comment by jaredLunde** [comment]
So I think I've fixed this in `3.0.4`, though I have a feeling the interop between touch/mouse will never be perfect. I'm still noticing difference between the way Safari on iOS and Chrome on my desktop are handling the overflow.

**Comment by alielkhateeb** [comment]
@jaredLunde Yes that's awesome, it's working fine, thanks.

Hmm, I think the issue is [here](https://github.com/jaredLunde/react-hook/blob/master/packages/mouse-position/src/index.ts#L60) because according to [caniuse TouchEvent API: touches](https://caniuse.com/#feat=mdn-api_touchevent_touches), it is not supported in any Safari version yet, I think we should find a way to workaround detecting if it's a `TouchEvent` or a `MouseEvent` in Safari.

I guess in any safari `isTouch` is always `false` so it never actually shims `mouseleave` event.
