### ISSUE TITLE
@react-hook/window-size: width and height are not synced causing an extra re-render

### ISSUE THREAD

**Issue by karland** [jaredLunde/react-hook#17]
Hi, thanks  for the library. It's super helpful.

I am using 

```JSX
const [width, height] = useWindowSize()
```

However, as it turns out `width` and `height` are not in sync, which means that I get a new width, but still have the old height. As a consequence, when I am changing the screen size, my component re-renders two times instead of one time. It first re-renders for width and then for height. I have come up with the following workaround, but I do not really like it:

```JSX
import { useState, useEffect } from "react"
import { connect } from "react-redux"
import { useWindowSize } from "@react-hook/window-size"
import { windowSizeUpdate } from "../../redux/actions/settings"

const DeviceSize = ({ dispatch }) => {
  const [width, height] = useWindowSize()
  const [windowSize, setWindowSize] = useState({ width, height })

  useEffect(() => {
    if (width !== windowSize.width) {
      setWindowSize({ width, height })
    } else if (height !== windowSize.height) {
      setWindowSize({ width, height })
    } else if (width !== height && windowSize.width !== windowSize.height) {
      let payload = { windowSize }
      dispatch(windowSizeUpdate(payload))
    }
  }, [dispatch, windowSize, height, width])

  return null
}

export default connect()(DeviceSize)
```

Is there a fix for this behaviour or a better solution? Thanks a lot.

**Comment by jaredLunde** [comment]
What requirement does your app have that makes it necessary for these values to be perfectly in sync? How often is the window size changing, such that two renders becomes a problem?

**Comment by karland** [comment]
Thanks for you answer. In the app, re-rendering is expensive. I noticed the unexpected behaviour when I turned tablets from landscape into portrait and vice versa. In these cases the re-rendering felt odd and I wondered why. It first re-rendered into a square, because the width changed and the height stayed and then from the square into the final format. This is why I had to do the workaround.

**Comment by jaredLunde** [comment]
Hmm that does sound annoying. Sorry to hear that. I will put a small fix in for this today.

**Comment by jaredLunde** [comment]
Fixed this for you. Just upgrade to `@react-hook/window-size@1.0.13`

**Comment by karland** [comment]
Wow. I saw the commit and it wasn't a short one. Thank you, thank you! 
This is most awesome. I tested it and it works perfectly.
