### ISSUE TITLE
react-hook/hover: ref type is incompatible

### ISSUE THREAD

**Issue by shatee** [jaredLunde/react-hook#18]
ref of return type of useHover is not compatible to  React Ref.

useHover's ref: `(element: HTMLElement) => void`

suggestion: `(element: HTMLElement | null) => void`

**Comment by jaredLunde** [comment]
submit a PR, thanks

**Comment by jaredLunde** [comment]
Fixed in 2.1.0

**Comment by shatee** [comment]
thank you!
