### ISSUE TITLE
useHover: Function components cannot have refs. Did you mean to use React.forwardRef()?

### ISSUE THREAD

**Issue by konsumer** [jaredLunde/react-hook#2]
You can see the issue [here](https://codesandbox.io/s/festive-kepler-5998s).

This code works fine (to validate the styled component functionality):

```js
const App = () => (
  <div>
    <Help visible={false}>HELP HERE</Help>
    <h1>Hello</h1>
  </div>
)
```

**Comment by jaredLunde** [comment]
You have the incorrect deconstructed order :)

`const [vis1, refVis1] = useHover(200, 200);`
should be 
`const [refVis1, vis1] = useHover(200, 200);`

Happy to help!

**Comment by konsumer** [comment]
Ah, you are right. Sorry, I was evaluating a few hover-hook libs. that [totally works](https://codesandbox.io/s/upbeat-dirac-e488d)
