### ISSUE TITLE
Allow opting out of @juggle/resize-observer polyfill

### ISSUE THREAD

**Issue by jsamr** [jaredLunde/react-hook#205]
**Is your feature request related to a problem? Please describe.**
The footprint of `@react-hook/resize-observer` is 86% occupied by its dependency on the `@juggle/resize-observer`. For those who don't need a polyfill, it's just a waste of resources:

![image](https://user-images.githubusercontent.com/3646758/173230448-5b731321-b526-406c-8562-411108d454be.png)

Source: https://bundlephobia.com/package/@react-hook/resize-observer@1.2.5

**Describe the solution you'd like**

Move the polyfilled version to a separate library to keep the original lib slim.

**Comment by jaredLunde** [comment]
IME it's in your bundle somewhere anyway,but I hear you and I'd be ok with a new major version that makes the user provide any polyfills via options

**Comment by jsamr** [comment]
@jaredLunde Thank you so much! And grateful for your valuable contributing to react ecosystem.
