### ISSUE TITLE
[Mouse Position] `isDown` is never true on mobile

### ISSUE THREAD

**Issue by Xananax** [jaredLunde/react-hook#29]
on Mobile, `isDown` is never true. Pressing triggers `isOver` only.

**To Reproduce**
1. Open https://r0xlt.csb.app/ on your mobile (or open devTools and toggle the mobile emulator)
2. Tap and drag
3. Notice that `isOver` is true, but `isDown` is not true

The code is available [here on CodeSandbox](https://codesandbox.io/s/epic-rosalind-r0xlt?file=/src/App.js) (a small change from the README example). Relevant part reproduced here for convenience:

```js
const App = () => {
  const [mousePosition, ref] = useMousePosition()
  return <div ref={ref}>
      isOver: {mousePosition.isOver ? 'true' : 'false'}<br/>
      isDown: {mousePositition.isDown ? 'true' : 'false'}<br/>
    </div>
}
```

**Expected behavior** 
"hover" state can't be detected on mobile, obviously, but `isDown` should be true if the user has tapped. Without it, it's impossible to detect a drag or long press.

**Comment by jaredLunde** [comment]
Thanks for the report! I would very much appreciate the PR 👍

**Comment by Xananax** [comment]
While continuing to use the library, I noticed a few other things that could be improved, I included them in the PR. Hope it's not too forward!
