### ISSUE TITLE
google-optimize: Causes error when window.gtag is not defined

### ISSUE THREAD

**Issue by jnv** [jaredLunde/react-hook#31]
Hi! I use Google Optimize with Google Tag Manager which doesn't expose `window.gtag` function. When I attempt to use `@react-hook/google-optimize` it errors with `window.gtag is not a function` 

1. Setup React application with Google Tag Manager following the [Quickstart Guide](https://developers.google.com/tag-manager/quickstart)
2. Use the `useGoogleOptimize` hook with any settings.
3. Open the page.
4. Application crashes with error: `Uncaught TypeError: window.gtag is not a function`

**Expected behavior**
I would expect no crash.

**Additional context**
I suspect the implementation is incomplete or tested only with the older Google Analytics script. Looking at the [Optimize documentation](https://support.google.com/optimize/answer/9059383?hl=en) mentioned in the source, there is this line as a kind of forward-compatibility shim:

```js
// Not required if the Google Analytics gtag implementation is used.
function gtag() {dataLayer.push(arguments)}
```

Though I think this is outdated since even Analytics now recommend to use GTM by default.

I think the preferred change here is to use `window.dataLayer` directly but also check for its existence (there may be cases where the client is missing GTM and therefore `dataLayer` property, either through intentional blocking or network failure).

**Comment by jaredLunde** [comment]
getting out a fix for this shortly

**Comment by jaredLunde** [comment]
Published as `@react-hook/google-optimize@1.1.0`. Please let me know if this version fixes your issue.

**Comment by jnv** [comment]
Thanks for a quick fix! Looks good, but there seems to be still a leftover in callback removal: https://github.com/jaredLunde/react-hook/blob/38fcd8280104a5a542f6739ff5c6ddb25c4ec88d/packages/google-optimize/src/index.ts#L40

**Comment by jaredLunde** [comment]
Ah, yikes. Thanks for noticing. Fixed this with `1.1.1`

**Comment by jnv** [comment]
Also, I have found one more issue which is basically GTM's weird behavior. Apparently the source snippet isn't just outdated by using `arguments` object – apparently GTM treats it differently from rest parameters.

Basically if I define the `gtag` wrapper like this:

```js
function gtm (...args) { window.dataLayer.push(args) }
```

no event goes to GTM. However if I do this:

```js
function gtm () { window.dataLayer.push(arguments) }
```

it works as expected. I think that GTM attempts explicitly identifies arguments object and treats it differently from a normal array.

I can forego the `gtag` by pushing to dataLayer directly, I just need to wrap callback into an `eventModel`:

```js
window.dataLayer.push(
{
  event: 'optimize.callback',
  eventModel: {
    callback: (value, name) => { console.log('Experiment with ID: ' + name + ' is on variant: ' + value)}
  }
}
)
```

**Comment by jaredLunde** [comment]
Thanks for digging into this. That's less than ideal about the arguments. 

Definitely open to adding it to the dataLayer directly. Feel free to submit a PR for that if you want credit, otherwise I will wait for any updates here.

**Comment by marcus13371337** [comment]
@jnv Found your solution while debugging our setup. Thanks for the solution! Have been debugging for hours, gtm/dataLayer works really weirdly sometimes 😀
