### ISSUE TITLE
`useResizeObserver` should use `disconnect` method for the observer when unmounting

### ISSUE THREAD

**Issue by yairEO** [jaredLunde/react-hook#312]
Currently the unmount logic within the `useResizeObserver` hook is calling the oberver's `unsubscribe` method which requires a DOM not as a parameter. This is both useless and also probably not correct because if the component unmounted than the DOM node which is being observed probably is longer in the DOM.

The `disconnect` method is the correct one to use in cases.

Opening a PR

**Comment by jaredLunde** [comment]
You're just very wrong about this and unfortunately I don't have time to explain it to you right now. Have another look at the code, consider where `targetEl` is coming from and how memory works in JavaScript etc. etc. etc.

**Comment by yairEO** [comment]
You are correct and have my deepest apology. 

I did not bother to look deeper and see that indeed the same observer was used. Sorry to have wasted your time.
