### ISSUE TITLE
resize-observer: window is not defined

### ISSUE THREAD

**Issue by ethteck** [jaredLunde/react-hook#315]
**Describe the bug**
In my Next.js [project](https://github.com/decompme/decomp.me), after updating to 2.x of resize-observer, my project won't build. The resulting js seems to assume "window" is defined, but the server-side compiling that happens in their system doesn't have `window` defined I guess. Sorry for the lack of details and clarification.. I am not really a web guy and barely understand what's going on here.

However, when [this check
](https://github.com/jaredLunde/react-hook/commit/80d260a2a2ad67b52cf828a15c2a2dadbbc417e5#diff-e2a59fd6f2649f4aac9ac02356147027937fd241092a13069afa659db2215892L12) to make sure window is defined was removed, it seems that broke whatever next.js is doing. Would it be possible for a check like this to be added back?

**Comment by jaredLunde** [comment]
https://github.com/jaredLunde/react-hook/issues/314

**Comment by ethteck** [comment]
ah, whoops! didn't see that. thanks :)
