### ISSUE TITLE
Looking for change log or why the breaking change (in window-size)?

### ISSUE THREAD

**Issue by axe312ger** [jaredLunde/react-hook#34]
I see the window-size bumped to version 3 in one of my projects. I struggle to find a change log, release information or migration instructions.

Can you please elaborate what was changed that might break projects using this dependency?

`@react-hook/window-size   latest  2.1.1    ❯  3.0.6    https://github.com/jaredLunde/react-hook/tree/master/packages/window-size#readme`

Thanks a bunch

**Comment by jaredLunde** [comment]
v2 signature:
```tsx
useWindowSize(
  initialWidth?: number, 
  initialHeight?: number, 
  {['fps' | 'wait']?: number, leading?: boolean}
)
```

v3 signature:
```tsx
useWindowSize({
  initialWidth?: number, 
  initialHeight?: number, 
  ['fps' | 'wait']?: number, 
  leading?: boolean
})
```
