### ISSUE TITLE
useDebounce() only supports initialValue and not value as input, so it may be unnecessarily verbose, without providing immediate state

### ISSUE THREAD

**Issue by scscgit** [jaredLunde/react-hook#35]
Hook `useDebounce(initialState, wait?, leading?)` uses initial state property as a first param (which lacks description in Readme and can feel ambiguous until tested), unlike some other debounce implementations like:
https://usehooks.com/useDebounce/
https://github.com/xnimorz/use-debounce
which use the input value directly instead. If this decision was made intentionally, I would suggest that the intended use-case could be at least addressed in the documentation, because right now if the user prefers a behavior where they can access both the immediate and debounced inputs (for example to do immediate client-sided validation but also debounced server-sided calls), the least verbose solution (using also a state hook) is probably writing the following block:
```
const [debouncedInput, setDebouncedInput] = useDebounce(input);
setDebouncedInput(input);
```
Note that this doesn't really feel optimized due to the fact that you have to call the setter outside a hook, so the user may assume some additional overhead and not feel comfortable about it, as there's nothing similar documented yet. Note that with input as a parameter, there wouldn't be any need to expose it also as an output; yet under the current implementation, it may actually make sense to also **return the immediate state, for example as a third (optional) array output parameter**, which would cover both use-cases with a single hook call (not requiring a setter or a second state hook). Of course, the alternative of turning `initialState` into `state` would require either adding a parameter (like `onlyInitialState=true`), or adding a **new function** with a new name, otherwise the forward compatibility would be threatened.

* (Though it could be theoretically argued that users don't have too much motivation behind using non-constant initialValue - if they provide a variable solely because they can't afford having an empty state before calling a setter for the first time, as the input default isn't `''`, doesn't this mean it's already too late at the moment of hook usage, and they can supply the new state anyway? Also there's no way to **immediately set** an initial state at a later point, should the user prefer some lazy initialization).

Because I don't want to claim that one approach is better than the other one, I'd rather like to have the intended use-cases covered by the documentation, so that if there are some obvious situations where this implementation isn't supposed to fit in, you could at least direct new users to an alternative library. For now I'm assuming that you want to cover all of the basic debounce use-cases, considering the intention conveyed by the **react-hook** namespace :)

**Comment by jaredLunde** [comment]
Other implementations are dumb. They don't debounce setting state, they only debounce using it. So rerenders in hooks still happen countless times. If you prefer the other implementations - use those. Pretty simple my friend.

**Comment by scscgit** [comment]
@jaredLunde Interesting point of view that "other implementations are dumb" :) That's even more of a reason why I'd prefer this reasoning to be at least **documented** a little bit on the API usage page for other people, who are deciding about which library to use in their project, because it obviously **doesn't seem to be trivial**. It's not about me having any preference, but rather just about providing new users with the opportunity to make an informed and unbiased decision. Nevertheless, I didn't quite understand why you rejected the generic use-cases, which I presented from the point of view of a library user. More specifically, it seemed to me that adding a third optional output in the form of `[state, setState, immediateState]` would cover all scenarios with the least overhead, so could you at least explain your assumptions (for other issue readers) of why do you see this as unreasonable, or where's the boundary of what isn't supposed to be covered by a library? Also when it comes to your statement that _"they only debounce using it"_, I don't really understand what makes the example implementation from my first link wrong if it uses `useEffect` with value in the deps parameter. Thanks for your time, hopefully the analysis in this suggestion was constructive at all (and can be generalized later) :)

**Comment by jaredLunde** [comment]
Here’s the thing, though: I don’t make these libraries for you, I make them for me and it’s merely your freedom to use them. I don’t care about covering all cases, I care about covering mine. If you think the docs are insufficient I welcome that PR! I think they’re pretty clear about it being a debounced version of the React.useState() hook.

**Comment by scscgit** [comment]
Of course, this was just a suggestion and I'm not forcing any responsibility on you. I was just curious about the specifics of what you explicitly criticized about the debounce alternatives in case there's anything objectively wrong, and to be honest, I'm also beginning to prefer your approach over them. That's why it'd be great if you could specify for example how would you **usually handle** these use-cases using your library. Would you follow my example from the first post, implement a new hook, or avoid the situation by different means? After all, there's a **paradox** in following your suggestion, as I'm unable to update a documentation via PR if its content has to include the details of intention, or the technical reasons, which you don't share ;) But don't worry, this doesn't need any priority, and I understand if there's a reason it would take you an effort to address this. (I just didn't find any evidence in the docs to assume that you don't intend to discuss and improve the hooks anymore.) Thanks for your time! :)

**Comment by jaredLunde** [comment]
Consider the cases:

```js
const useMouseEvent = () => {
   const [event, setEvent] = React.useState({})
   const debouncedEvent = useDebounce(event)

   React.useEffect(() => {
     window.addEventListener('mousemove', setEvent)
     () => window.removeEventListener('mousemove', setEvent)
   }, [])

   return debouncedEvent
}
```

^ That hook will still re-render EVERY TIME the event is fired. That's terrible for performance and `mousemove` is an **expensive** event.

Now consider my approach:

```js
const useMouseEvent = () => {
   const [debouncedEvent, setEvent] = useDebounce({})

   React.useEffect(() => {
     window.addEventListener('mousemove', setEvent)
     () => window.removeEventListener('mousemove', setEvent)
   }, []) 

   return debouncedEvent
}
```

^ That **only** sets state when the debounce wait time is surpassed. The number of renders in a 100ms span assuming a 100ms wait time is 1 for my hook and potentially hundreds for the alternative.

I hope this helps!

**Comment by jaredLunde** [comment]
If I add the `immediateState` you request that optimization is bunk. It's gone.
