### ISSUE TITLE
Does useMediaQuery optimize multiple calls?

### ISSUE THREAD

**Issue by slavafomin** [jaredLunde/react-hook#50]
Hello!

Thank you for this great library!

However, when you have a lot of components that call `useMediaQuery()` with the same attributes does it optimize such calls somehow?

The `use-media` library has [a recommendation](https://github.com/streamich/use-media#storing-in-context) regarding the context usage to optimize such calls. Is it required with `useMediaQuery()`?

Thanks!

**Comment by jaredLunde** [comment]
There's not really a way to accomplish shared listeners without using subscriptions outside of React. [That's the approach I use with useResizeObserver()](https://github.com/jaredLunde/react-hook/blob/master/packages/resize-observer/src/index.tsx#L55), however, I do not do so with this hook. I think the library you linked has a good solution in this case.
