### ISSUE TITLE
usePassiveLayoutEffect webpack error in production build

### ISSUE THREAD

**Issue by Druux** [jaredLunde/react-hook#51]
**Describe the bug**
Getting a super weird error when building with webpack in production mode.

`passive_layout_effect_dist_module is not a function.`

Have you guys already experienced something like that? Could someone point me in the right direction maybe?

**Comment by skoob13** [comment]
I'm getting the same issue using Webpack 5. Downgrading to Webpack 4 solves the issue. I suppose Webpack 5 does tree shaking differently and removes hooks.

Repro on [Codesandbox](https://codesandbox.io/s/peaceful-thompson-0h4jh?file=/package.json):
1. [Webpack 5](https://csb-0h4jh-5vqa6sdyn.vercel.app/)
2. [Webpack 4](https://csb-0h4jh-qmpjii4oy.vercel.app/)

I found two ways to fix the issue:
1. Replace the React wildcard import to default
2. Remove the bracket notation:

```
const usePassiveLayoutEffect =
    typeof document !== 'undefined' && document.createElement !== void 0
      ? React.useLayoutEffect
      : React.useEffect
```

I can submit a PR.

Btw, thank you for your great work!

**Comment by jaredLunde** [comment]
Go ahead and submit a PR replacing the wildcard import. I really appreciate your digging into this! Really tired of these wildcard/default interop bundler wars 😑
