### ISSUE TITLE
IE11 crashes with syntax error in the intersection-observer package

### ISSUE THREAD

**Issue by aolde** [jaredLunde/react-hook#55]
**Describe the bug**
The main bundle of the @react-hook/intersection-observer package uses arrow functions that makes IE11 crash with syntax error.

Example `dist/main/index.js`:

```js

const useIntersectionObserver = (target, options = {}) => {
  //                                      ERROR HERE --^^
  const {
    root = null,
    pollInterval = null,
    useMutationObserver = false,
    rootMargin = '0px 0px 0px 0px',
    threshold = 0,
    initialIsIntersecting = false
  } = options;

  // ...
}
```

**To Reproduce**
1. Load a page using this package in IE11, that is using the main package bundle.
2. A syntax error is thrown.

**Expected behavior**
The main bundle should be transpiled to a version of JS that is supported by IE11.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: IE
 - Version: 11

**Comment by jaredLunde** [comment]
Not a bug: it is 100% your responsibility to compile dependencies to your desired target. Call it controversial if you want, that’s the stance I’ve always taken and I’m not changing it.

**Comment by erezcohen** [comment]
This should be stated clearly in the README IMO.
I respect your decision to be shipping +ES6 only however I have no way of knowing it without starting to dig into (closed) issues and code.
We have hundreds of packages in our project and they all ship ES5.

**Comment by jaredLunde** [comment]
I don't care about IE11. Compile your node_modules to your desired target yourself like CRA does.

**Comment by jaredLunde** [comment]
Like, read my other comment. What makes you think you're going to change my mind? Use another library if you don't like it. I don't work for you. I work for me. Get over it.

**Comment by jaredLunde** [comment]
Now included in the README: https://github.com/jaredLunde/react-hook/blob/master/README.md#note-on-ie11
