### ISSUE TITLE
Intersection Observer - thresholds param bug

### ISSUE THREAD

**Issue by jorhelbdr** [jaredLunde/react-hook#56]
Hi,

Thank you for these handy hooks !

I think there is a problem with `thresolds` param. 
It only works if I use `threshold`, not `thresholds` as explained in the documentation.

**Comment by jaredLunde** [comment]
Oh whoops, sorry about that! `threshold` is correct. I will update the docs today.

**Comment by jaredLunde** [comment]
Fixed, thanks for reporting!
