### ISSUE TITLE
[Types] IntersectionObserverOptions.threshold prevents number[]

### ISSUE THREAD

**Issue by Dangoo** [jaredLunde/react-hook#61]
Hi there, observed the following inconsistency:

**Describe the bug**
According to the [documentation](https://github.com/jaredLunde/react-hook/blob/master/packages/intersection-observer/README.md#intersectionobserveroptions) `IntersectionObserverOptions.threshold` can be either `number | number[]`.
But the [types](https://github.com/jaredLunde/react-hook/blob/master/packages/intersection-observer/types/index.d.ts#L12) only allow for type `number`.

**To Reproduce**
1. Call `const test = useIntersectionObserver(null, {threshold: [0, 1]})`
4. See error `Type 'number[]' is not assignable to type 'number'.ts(2322)`

**Expected behavior**
The options object should accept type `number[]`

Would you be open for a PR?

**Comment by jaredLunde** [comment]
Documentation is wrong
