### ISSUE TITLE
Add event options for useEvent

### ISSUE THREAD

**Issue by dzcpy** [jaredLunde/react-hook#73]
**Is your feature request related to a problem? Please describe.**
Currently it's not able to pass event options
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#parameters
**Describe the solution you'd like**
Add an option, so for example it can listen passively if set the listem mode to passive.
**Describe alternatives you've considered**
Using `react-use` module
**Additional context**

**Comment by jaredLunde** [comment]
ya I'm aware of the options. I rarely need them and thus do not care. Feel free to use react-use.
