### ISSUE TITLE
[useResizeObserver] Use border-box instead of content-box

### ISSUE THREAD

**Issue by bhollis** [jaredLunde/react-hook#75]
**Is your feature request related to a problem? Please describe.**

[`getBoundingClientRect`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) returns the `border-box`, which includes padding and borders. However by default [`ResizeObserver.observe`](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver/observe) uses the `content-box`, which does not. This renders the example for [`useResizeObserver`](https://github.com/jaredLunde/react-hook/tree/master/packages/resize-observer#readme) incorrect as it'll set the size with padding, then update to the size without padding. `useSize` avoids this by using `offsetWidth` and `offsetHeight`.

**Describe the solution you'd like**

Either pass the `content-box` option to `ResizeObserver.observe`, or change the example in the README to not use `getBoundingClientRect`.

**Describe alternatives you've considered**
I just switched to reading `offsetHeight` like `useSize` does.

**Comment by jaredLunde** [comment]
afaik `border-box` is experimental and not widely supported. if you can show me something showing it has wide support, by all means.

**Comment by bhollis** [comment]
If ResizeObserver.observe's options parameter is not widely supported, then the solution would be to update the example in the README to use offsetWidth and offsetHeight instead of getBoundingContentRect.

**Comment by jaredLunde** [comment]
feel free to update the README, I personally see nothing inaccurate about it.

**Comment by isc30** [comment]
@bhollis is right, the example uses the BoundingClientRect (border-box) for the initial size and later on the resize handler it uses the contentRect (content-box)
